# Basic concepts {.unnumbered}
Research data play a foundational role in Social Science and Humanities research, providing the scientific evidence for confirming hypotheses, backing claims and, more in general, substanciating research. 

This guide assumes certain concepts, and related definitions, provided here for reference.

## Research Data

::: {.callout-note icon=false appearance="simple"}

_**Research data** is all information intentionally collected, observed, or generated to validate research findings and substanciate scientific claims._[^1]

:::

Data can be [quantitative](https://en.wikipedia.org/wiki/Quantitative_research){target="_blank"} or [qualitative](https://en.wikipedia.org/wiki/Qualitative_research){target="_blank"} in nature and take the forms of tables, text, images, audio/video recordings, archival material and other sources or physical evidence. 

Similar definitions are available online.[^longnote]

## Research Data Lifecycle

::: {.callout-note icon=false appearance="simple"}

*The **Research Data Lifecycle** describes the different stages research data go through before, during, and after a research project. The research data lifecycle includes everything from planning how data will be collected, to publication, to long-term data preservation, to possible reuses of data.* 

:::

For this quide we adopt the following **Research Data Lifecycle** model[^2]:

[add image here, adapted from RDMkit]
<!-- In this section, information is organised according to the stages of the research data life cycle. You will find:
- A general description and introduction of each stage.
- A list of the main considerations that need to be taken into account during each stage.
- Links to training materials related to each stage.
- Links to related data management tasks that can be performed at each stage.
- Links to a Data Stewardship Wizard for your DMP and to step-by-step instructions to make your data FAIR. -->

## Research Data Management (RDM)

::: {.callout-note icon=false appearance="simple"}

_**Research Data Management (RDM)** is an umbrella term covering how you organise, structure, store, and care for the digital information generated or used during a research project._

:::

 RDM practice usually includes:

- Planning in advance how your data will be managed
- Documenting working practices
- Considering how information will be handled on a day-to-day basis
- Making decisions on what happens to data in the long term –  after the project concludes
- Preparing for data to be preserved
- Considering whether the information may be reproducible[^3]


[^1]: The European Commission, under their Q&A on Open Science requirements for funded projects defines research data as "the information (facts or numbers) collected to be examined and considered, and to serve as a basis for reasoning, discussion or calculation." [https://rea.ec.europa.eu/open-science_en](https://rea.ec.europa.eu/open-science_en){target="_blank"}
[^2]: Model adapted from [RDMlit](https://rdmkit.elixir-europe.org/data_life_cycle){target="_blank"}
[^3]: We adopted the definition from Research Data Oxford [https://researchdata.ox.ac.uk/about-data-management](https://researchdata.ox.ac.uk/about-data-management){target="_blank"}]