# Data Management Plan (DMP) {.unnumbered}

::: {.callout-note icon=false appearance="simple"}

_A **Data Management Plan (DMP)** is a formal document that outlines how data will be handled during and after a research project._

:::

Data Management Plans (DMPs) are documents normally required by research funders at the beginning, mid-point and end of research projects. A DMP is a living document that usually includes the following information:

- How data is collected and generated
- How data is used, elaborated and organised
- How data, and data subjects, are protected
- How data, code and ancillary elements are described and documented
- How data is stored and secured during the project, and how long it will be retained
- How dataset authorship and credit are assigned
- How data is preserved
- How, whether and under what terms, research data outputs can be shared


::: {.callout-tip}
Preparing a DMP at the beginning of a research endeavour is an important step in making sure that data are properly managed and curated, prepared for possible [sharing and reuse](links), and in ensuring [transparency and reproducibility](link) of research. Early-stage researchers (like EUI PhD Researchers) are strongly invited to learn how to prepare a DMP, as they will be required when applying for future project funding.
:::

## Preparing a Data Management Plan (DMP)]

Every DMP is a unique document, grounded in the individual research project and it is the responsibility of the Principal Investigator (PI), or delegated person (e.g. the project manager, or member of the research team) to write and deliver a comprehensive, accurate and original data management plan.

The FAIR data principles - to make data findable, accessible, interoperable and reusable - must be considered during the preparation and revision of data management plans. Detailed information about these four principles is available in the grid below.

The following supporting materials should be consulted during the preparation of EUI DMPs:

- [EUI Code of Ethics](https://www.eui.eu/ServicesAndAdmin/DeanOfStudies/Ethics-and-Integrity-in-Academic-Research)
- [**EUI 'Guide to Good Data Protection Practice in Research**](https://www.eui.eu/documents/servicesadmin/deanofstudies/researchethics/guide-data-protection-research.pdf)
- [**EUI Guidelines on Ethics and Integrity in Academic Research**](https://www.eui.eu/ServicesAndAdmin/DeanOfStudies/Ethics-and-Integrity-in-Academic-Research)
- [**EUI Library Research Data Guide**](/) (this guide) 

Scholars preparing a data management plan for funded projects should also carefully follow the instructions provided by the relevant science programme office (eg. **Horizon Europe**, **European Research Council** etc.). Where a DMP template is provided, this must be used, for example: 

- [Horizon Europe DMP template](https://ec.europa.eu/info/funding-tenders/opportunities/docs/2021-2027/horizon/temp-form/report/data-management-plan_he_en.docx) in the [Horizon Europe Work Programme](https://ec.europa.eu/info/funding-tenders/opportunities/docs/2021-2027/horizon/guidance/programme-guide_horizon_en.pdf)
- [ERC DMP template](https://erc.europa.eu/sites/default/files/document/file/ERC-Data-Management-Plan.docx) in the [ERC Work Programme](https://ec.europa.eu/info/funding-tenders/opportunities/docs/2021-2027/horizon/wp-call/2022/wp_horizon-erc-2022_en.pdf).

**It is important to update DMPs throughout the research project**, incorporating new information about data collection,
data generation, methodologies and relevant changes to the composition of the research team or consortium (for intenrational collaborative projects).

::: {.callout-tip}

The EUI Library can provide feedback and guidance. Please, reach out to the [Research Data Librarian](mailto:resdata@eui.eu)

:::

## Common elements of a DMP
When preparing a DMP scholars can follow these prompts to address all core aspects:

::: {.callout-note icon=false appearance="simple"}

## Overview of research project

-   Provide an overview of the research project, indicating discipline/sub-discipline, inter-disciplinary scope, methodology and primary research questions           
-   List the types of data being collected, generated, processed and used.        

:::

::: {.callout-note icon=false appearance="simple"}

## Anticipated data outputs and utility

-   Describe expected data outputs
-   Distinguish (where applicable) between (i) in-project data which 
    will not be shared and (ii) post-project research dataset outputs
    (public or embargoed)                                                                   
-   Describe expected public utility; eg. for researchers,           
    policymakers, media organisations and the general public
-   Describe possible inter-disciplinary use
-   Describe data quality assurance processes.

:::

::: {.callout-note icon=false appearance="simple"}

## Resources required for data collection, generation, processing and use

-   Provide a detailed description of data collection, generation,
    processing and use
-   Describe anticipated technical and research assistance        
    requirements
-   Give an overview of the data management responsibilities of   
    research project leaders, team members and (where applicable) 
    institutional partners.                                       

:::

::: {.callout-note icon=false appearance="simple"}

## Data security, infrastructure and protocols

-   EUI members should write to the [Data Security Officer](https://www.eui.eu/About/SafetySecurity/Data-Security-Officer) to request the standard description of data security, infrastructure and protocols. This internal document describes layered physical and network security, authentication protocols and other elements for inclusion in data management plans.                          

:::

::: {.callout-note icon=false appearance="simple"}

## Ethical considerations

-   Describe data protection measures in place to scrupulously guarantee that persons, families and households are not identifiable in any dataset outputs
-   EUI Ethics Committee review may be required before the collection and processing of personal data. Ethics Committee approval cannot be granted retroactively. EUI members should [initiate the request for Ethics Review](https://www.eui.eu/ServicesAndAdmin/DeanOfStudies/Procedure-to-request-an-Ethics-Review-by-the-EUI-Ethics-Committee) before collecting data.
-   Consultation with the EUI Data Protection Officer and/or Data Security Officer may be required (included in the Ethical Review).
-   Maintain a record of pre-existing data resources used in the project, and comply with copyright provisions.
-   Contact the [Research Data Librarian](mailto:resdata@eui.eu) for assistance.                              
:::

## FAIR principles in DMPs

Most funding programmes, including ERC and other Horizon Europe schemes, have embraced the principles and practices of **Open Science**, fostering the approach that data should always be "*as open as possible and as closed as necessary*".

The **FAIR principles** have been adopted as a guiding rubric in DMPs to ensure that research data are effectively **F**indable, **A**ccessible, **I**nteroperable and **R**eusable. The FAIR principles also shaped the most recent version of the DMP templates for ERC and Horizon Europe.

Here following a few elements that **Principal Investigators** and **Project Managers** have to consider when addressing the FAIR principles in their DMP:

::: {.callout-note icon=false appearance="simple"}


:::

::: {.callout-note icon=false appearance="simple"}

## Making data Findable

-   Identify the repository where data outputs will be preserved and,
    where possible, made openly available; eg. the EUI research      
    repository, Cadmus.
-   Describe how folders, files, variables and versions will be      
    consistently named to aid discovery
-   Datasets should be assigned accurate and consistent metadata to  
    aid findability and machine-retrievability (Section 6.c)
-   Datasets should have persistent, unique digital object           
    identifiers (eg. handles generated by the EUI research           
    repository, Cadmus).                                             

:::

::: {.callout-note icon=false appearance="simple"}

## Making data Accessible

-   Distinguish between in-project data which will remain closed (or 
    will be destroyed) after the project; and data outputs which will
    be preserved and (where possible) openly shared after the project
-   For restricted data, give reasons for restricted status (eg.     
    personal data protection and/or database copyright compliance)
-   For restricted data the terms and conditions for access should be
    explicitly stated (even if these might be revised as the research
    progresses)
-   For sharable data, the status 'open' (accessible immediately) or 
    'embargoed' (accessible at a later date) should be assigned
-   Describe data protection and anonymisation measures in detail
-   Describe the software packages/tools required to use the data
-   Metadata records are indexed in the EUI research repository,     
    Cadmus, which provides machine-readable metadata for indexing by 
    search engines and application programming interfaces (eg. Google
    Scholar, OpenAIRE and CORE).                                     

:::

::: {.callout-note icon=false appearance="simple"}

## Making data Interoperable

-   Provide details of any standard controlled vocabularies (ontologies, thesauri and taxonomies) from the relevant discipline (social sciences, humanities, ethnography &c.)
-   Variable schemas should be readable by standard software packages to facilitate data interoperability
-   Standard metadata and naming conventions should be used
-   The EUI research repository, Cadmus, uses web standards (the underlying DSpace software adopts standards for embedded micro-data and the OAI-PMH interoperability protocol) providing both human- and machine-readable interfaces to search, discover and access reposited data.

:::

::: {.callout-note icon=false appearance="simple"}

## Making data Reusable

-   Open data generated by the research project should be made available under an open licence that clearly states reuse conditions - either the Creative Commons Attribution International license: CC-BY International[^49] or the Creative Commons Public Domain Universal license: CC0
-   Supporting documentation and codebooks (PDF/A documents and 'readme.txt' files) should be reposited with the data to make the observations comprehensible and reusable by other scholars and stakeholders
-   Provide information about any tools or instruments necessary to reuse or verify the data (software, algorithms, routines, models &c.)
-   Note any data embargo period, where applicable.                  

:::

## Data management planning tools

Online tools can be used to prepare structured data management plans -
complying with EU Horizon Europe, European Research Council, and other
science funder DMP requirements.

-   **DMPonline**[^53] (maintained by the Digital Curation Centre) can
    be accessed via 'Create Account' at the upper right of the DMPonline
    homepage. For organisation enter 'other'. Select the science
    funder\'s template. The principal investigator (P.I.) should be
    identified in the data management plan. For research teams, the P.I.
    can assign DMP sharing rights by entering colleagues' email
    addresses and assigning the status of 'co-owner', 'editor' or 'read
    only.' Enter project details (title, abstract, &c.) and click on
    'Initial DMP' in the top menu. Complete the sub-fields to generate
    the data management plan. A Word document can be generated. If the
    science funder provides a DMP template, the text generated in
    DMPonline can be transferred into the funder\'s template.

-   **The Research Data Management Organiser** (RDMO)[^54] is an online
    tool available in German and English to support research data
    management. RDMO is maintained by the Deutsche
    Forschungsgemeinschaft (DFG).

-   **Argos**[^55] is an online DMP creation tool maintained by
    OpenAIRE. Create an account on the Argos platform, click 'Launch
    Wizard' and follow the step-by-step instructions.

-   **The DMP Evaluation Rubric**[^56] developed by Science Europe,
    provides core criteria which can be used by principal investigators
    and project managers to evaluate data management plans.

-   **FAIRsharing** is a data support service of the Data Readiness
    Group and the Bodleian Library, University of Oxford, providing
    resources for data and metadata standards and research data
    management.[^57]

-   **The F**-**UJI Automated Fair Data Assessment Tool**[^58]
    maintained by the Fostering FAIR Data Practices In Europe project,
    helps scholars comply with the FAIR Guiding Principles for
    scientific data management that ensure data are - and remain -
    findable, accessible, interoperable and reusable (FAIR).

-   **FAIR**-**Aware**[^59] maintained by the Data Archiving and
    Networked Services Institute is an online checklist tool to help
    researchers build compliance with the FAIR data principles.

-   **The DMP Catalogue**[^60] maintained by LIBER, provides examples of
    research data management plans.