# Qualitative and unstructured data {.unnumbered}

This section treats qualitative data generation, use, preservation and access in the humanities and social sciences. Examples of qualitative data include; audio and audio-visual interviews, transcripts, images, minable text, survey diaries, field notes and multimedia materials. The definition of 'data' is broad, as it varies across academic disciplines (eg. history, ethnography, anthropology, sociology &c.). Data collection methodology, dataset structure and data documentation should conform to the best practices of the discipline in which the research is undertaken.[^104]

## Protection and ethical use of qualitative data

Scholars generating, accessing, processing and sharing qualitative data should pay particular attention to the data protection and ethical use provisions described in the EUI 'Guide to Good Data Protection Practice in Research'.[^105] Scholars are subject to data protection legislation when collecting, generating, processing, using and storing personal data. The processing of sensitive data relating to health, racial/ethnic origin, religious beliefs, political opinions, genetic/biometric observations, sexual orientation, memberships &c. may require EUI Ethics Committee clearance before data collection and processing begins.[^106] Ethics Committee approval cannot be sought retroactively. The Ethics Committee review can take up to six weeks. Principal investigators should consult the online Initial Checklist and the supporting documentation on the EUI information page for Ethics and Integrity in Academic Research.[^107] When collecting, processing, using and storing personal data, scholars are responsible for obtaining and documenting the informed consent of subjects. The EUI sample consent form can be used.[^108] Throughout the research data lifecycle, scholars are responsible for preserving the confidentiality of data observations pertaining to human subjects, families and households. Anonymisation and pseudonymisation techniques are described at Section 2.d above. Software such as the open source QualiAnon anonymisation tool can be used for the anonymisation and redaction of interview transcripts.[^109]

Scholars who intend to generate images, videos or photocopies of materials and objects in museums and archives, should seek the rights owners' permission in advance. Scholars who wish to reproduce pre-existing images or multimedia of such materials (eg. photographs in catalogues raisonne) should seek copyright clearance before reproducing.

Braukmann, R., Verburg, M., & Mahabier, W. (2024). Guidebook - Depositing Restricted Access In The DANS Data Stations (1.0). Zenodo. [https://doi.org/10.5281/zenodo.10887484](https://doi.org/10.5281/zenodo.10887484)